clinic/urls.py
from django.urls import include, path

from clinic import ExcelTemplate
from . import views,delete,imports,editView

urlpatterns = [
        path('',views.index, name="home"),    
        path('delete_medicine_route/',views.delete_medicine_route, name="delete_medicine_route"),       
        path('delete_medicine_unit_measure/',views.delete_medicine_unit_measure, name="delete_medicine_unit_measure"),
        path('add_medicine_unit_measure/',views.add_medicine_unit_measure, name="add_medicine_unit_measure"),
        path('add_medicine_route/',views.add_medicine_route, name="add_medicine_route"),
        path('medicine_routes/',views.medicine_routes, name="medicine_routes"),
        path('medicine-unit-measures/', views.medicine_unit_measures, name='medicine_unit_measures'),
        path('add_service/',views.add_service, name="add_service"),
        path('new_consultation_order/',views.new_consultation_order, name="new_consultation_order"),
        path('fetch_prescription_counts_view/',views.fetch_prescription_counts_view, name="fetch_prescription_counts_view"),
        path('fetch_order_counts_view/',views.fetch_order_counts_view, name="fetch_order_counts_view"),
        path('fetch_radiology_order_counts_view/',views.fetch_radiology_order_counts_view, name="fetch_radiology_order_counts_view"),
        path('fetch_procedure_order_counts_view/',views.fetch_procedure_order_counts_view, name="fetch_procedure_order_counts_view"),
        path('new_radiology_order/',views.new_radiology_order, name="new_radiology_order"),
        path('new_procedure_order/',views.new_procedure_order, name="new_procedure_order"),
        path('save_diagnosis/',views.save_diagnosis, name="save_diagnosis"),
        path('save_consultation_notes/',views.save_consultation_notes, name="save_consultation_notes"),
        path('save_patient_vital/',views.save_patient_vital, name="save_patient_vital"),
        path('add_prescription/',views.add_prescription, name="add_prescription"),
        path('delete_ambulance_activity/',views.delete_ambulance_activity, name="delete_ambulance_activity"),
        path('add-ambulance-activity/', views.add_ambulance_activity, name='add_ambulance_activity'),
        path('ambulance-activities/', views.ambulance_activity_list, name='ambulance_activity_list'),
        path('save_edited_patient/',views.save_edited_patient, name="save_edited_patient"),
        path('add_patient_visit/',views.add_patient_visit, name="add_patient_visit"),
        path('add_health_issue',views.add_health_issue, name="add_health_issue"),
        path('resa_clinic/dashboard',views.dashboard, name="dashboard"),
        path('fetch_model_data/', views.fetch_model_data, name='fetch_model_data'),
        path('resa/ImportExcel',views.import_staff, name="import_staff"),      
        path('pathology_diagnostic_test_save/', views.pathology_diagnostic_test_save, name='pathology_diagnostic_test_save'),
        path('save_consultation_data/', views.save_consultation_data, name='save_consultation_data'),
        path('add_disease/', views.add_disease, name='add_disease'),
        path('save_consultation_fee/', views.save_consultation_fee, name='save_consultation_fee'),
        path('add_insurance_company/', views.add_insurance_company, name='add_insurance_company'),
        path('add_company/', views.add_company, name='add_company'),
        path('add_pathodology_record/', views.add_pathodology_record, name='add_pathodology_record'),
        path('update_equipment_status', views.update_equipment_status, name='update_equipment_status'),        
        path('login', views.ShowLogin, name='login'),       
        
        path('logout_user', views.logout_user, name='logout_user'),  # Move this line here
        path('contact/', views.ContactFormView.as_view(), name='contact_form'),
        path('GetUserDetails', views.GetUserDetails, name='GetUserDetails'),
        path('add_patient/', views.add_patient, name='add_patient'),
        path('dologin', views.DoLogin, name='DoLogin'),
        path('save_usage_history/', views.save_usage_history, name='save_usage_history'),
        path('add_category/', views.add_category, name='add_category'),
        path('accounts/', include('django.contrib.auth.urls')),  
        path('resa/portfolio/details',views.portfolio_details, name="portfolio_details"),
        path('resa/contact',views.contact, name="contact"),
        path('resa/blog/single',views.blog_single, name="blog_single"),
        path('resa/page/404',views.page_404, name="page_404"),        
        path('resa/new-consultation',views.add_consultation, name="add_consultation"),
        path('staff_detail/<int:staff_id>/', views.single_staff_detail, name='single_staff_detail'),
        path('view-patient/<int:patient_id>/', views.view_patient, name='view_patient'),
        path('edit_staff/<str:staff_id>', views.edit_staff, name='edit_staff'),  
        path('edit_staff_save', views.edit_staff_save, name='edit_staff_save'), 
        path('delete_ambulance_route', views.delete_ambulance_route, name='delete_ambulance_route'),
        path('resa/new-request',views.add_request, name="add_request"),
        path('resa/add_or_edit_ambulance_route',views.add_or_edit_ambulance_route, name="add_or_edit_ambulance_route"),
        path('ambulance-routes/', views.ambulance_route_list, name='ambulance_route_list'),
        path('resa/update-staff-status',views.update_staff_status, name="update_staff_status"),
        path('resa/update_vehicle_status',views.update_vehicle_status, name="update_vehicle_status"),
        path('add_inventory/',views.add_inventory, name="add_inventory"),
        path('add_supplier/', views.add_supplier, name='add_supplier'),
        path('save_sample/',views.save_sample, name="save_sample"),
        path('save_patient_disease/',views.save_patient_disease, name="save_patient_disease"),
        path('save_service_data/',views.save_service_data, name="save_service_data"),
        path('save_staff_view/',views.save_staff_view, name="save_staff_view"),
        path('get_item_quantity/',views.get_item_quantity, name="get_item_quantity"),
        path('increase_inventory_stock/',views.increase_inventory_stock, name="increase_inventory_stock"),
        path('add_inventory_item/',views.add_inventory_item, name="add_inventory_item"),
        path('get_items_below_min_stock/',views.get_items_below_min_stock, name="get_items_below_min_stock"),
        path('add_equipment/',views.add_equipment, name="add_equipment"),
        path('use_inventory_item/',views.use_inventory_item, name="use_inventory_item"),
        path('add_reagent/',views.add_reagent, name="add_reagent"),
        path('increase_reagent_stock/',views.increase_reagent_stock, name="increase_reagent_stock"),
        path('add_reagent_used/',views.add_reagent_used, name="add_reagent_used"),
        path('add_maintainance/',views.add_maintainance, name="add_maintainance"),
        path('add_quality_control/',views.add_quality_control, name="add_quality_control"),
        path('quality_control_list/',views.quality_control_list, name="quality_control_list"),
        
        
        # reports urls 
        path('resa/resa-report',views.resa_report, name="resa_report"),       
        path('resa/reports-adjustments',views.reports_adjustments, name="reports_adjustments"),
        path('resa/reports-by-visit',views.reports_by_visit, name="reports_by_visit"),
        path('resa/reports-comprehensive',views.reports_comprehensive, name="reports_comprehensive"),
        path('resa/reports-patients-visit_summary',views.reports_patients_visit_summary, name="reports_patients_visit_summary"),
        path('resa/reports-patients',views.reports_patients, name="reports_patients"),
        path('resa/reports-service',views.reports_service, name="reports_service"),
        path('resareports-stock-ledger',views.reports_stock_ledger, name="reports_stock_ledger"),
        path('resa/reports-stock-level',views.reports_stock_level, name="reports_stock_level"),
        path('resa/reports-orders',views.reports_orders, name="reports_orders"),
        path('resa/individual-visit',views.individual_visit, name="individual_visit"),
        path('resa/product-summary',views.product_summary, name="product_summary"),        
        path('get_out_of_stock_count/',views.get_out_of_stock_count, name="get_out_of_stock_count"),
        path('resa/save-diagnostic-test',views.save_diagnostic_test, name="save_diagnostic_test"),
        path('resa/in-stock-reagent-view',views.in_stock_reagent_view, name="in_stock_reagent_view"),
        path('resa/out-of-stock-reagent-view',views.out_of_stock_reagent_view, name="out_of_stock_reagent_view"),
        
       
        
        # manage urls 
        # path('resa/remotemanage_patient/', views.remotemanage_patient, name='remotemanage_patient'),
       
        path('add_frequency/', views.add_frequency, name='add_frequency'),
        path('delete_frequency/', views.delete_frequency, name='delete_frequency'),
        path('orders/<str:date>/', views.orders_by_date, name='orders_by_date'),
        path('prescription-frequencies/', views.prescription_frequency_list, name='prescription_frequency_list'),
        path('diagnosis/', views.diagnosis_list, name='diagnosis_list'),
        path('all_orders_view/', views.all_orders_view, name='all_orders_view'),
        path('generate_invoice_bill/<int:order_id>/', views.generate_invoice_bill, name='generate_invoice_bill'),
        path('save_remotepatient_vital/', views.save_remotepatient_vital, name='save_remotepatient_vital'),
        path('save_remoteconsultation_notes/', views.save_remoteconsultation_notes, name='save_remoteconsultation_notes'),
        path('consultation-notes/', views.consultation_notes_view, name='consultation_notes'),
        path('resa/patient_vital_all_listt/', views.patient_vital_all_list, name='patient_vital_all_list'),

resaclinic/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from resaclinic import settings
from django.views.i18n import set_language
from clinic.views import logout_user
from clinic.views import DoLogin
admin.site.logout = logout_user
urlpatterns = [
     path('admin/login/', DoLogin, name='custom_login'),
    path('admin/', admin.site.urls, name='hmis_admin'),
    path('',  include(('clinic.urls', 'clinic'), namespace='clinic')),
    path('resa/', include('centric.urls')),
    path('reception/', include('resaclinic.receptionist_urls')),
    path('Pharmacy/', include('resaclinic.pharmacist_urls')),
    path('Lab/', include('resaclinic.labtechnician_urls')),
    path('doctor/', include('resaclinic.doctor_urls')),
    path('nurse/', include('resaclinic.nurse_urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('kahama/', include(('kahamahmis.urls', 'kahamahmis'), namespace='kahamahmis')),
    path('i18n/', set_language, name='set_language'), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    
admin.site.login = 'custom_login'
admin.site.index_title = "Resa Clinic "
admin.site.site_header = "Resa Clinic "
admin.site.site_title = "Resa Clinic "    

clinic/templates/update/edit_company.html
{% extends 'hod_template/base_template.html' %}

{% block page_title %}
  Edit Company
{% endblock page_title %}

{% block main_content %}
  {% load static %}

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <h2 class="card-header">Edit Company</h2>
            <div class="card-body">
              <form method="post" action="{% url 'clinic:edit_company' company.id %}">
                {% csrf_token %}
                <div class="row">
                  <div class="form-group col-sm-6">
                    <label for="Name" class="col-form-label">Name</label>
                    <input type="text" class="form-control" name="Name" id="Name" value="{{ company.name }}" placeholder="Enter name">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="code" class="col-form-label">code</label>
                    <input type="tel" class="form-control" name="code" id="code" value="{{ company.code }}" placeholder="Enter code">
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-sm-6">
                    <label for="category" class="col-form-label">Short name</label>
                    <input type="text" class="form-control" name="category" id="category" value="{{ company.category }}" placeholder="Enter category">
                  </div>            
                          
                </div>
                
                <div class="form-group row">
                  <div class="offset-md-6 col-md-6 text-right">
                    <button type="submit" class="btn btn-primary">Save and Continue</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="card-footer">
              <div class="form-row">
                <div class="col-12">
                  {% if messages %}
                    {% for message in messages %}
                      <div class="alert {{ message.tags }}">
                        {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock main_content %}

clinic/templates/update/edit_disease.html
{% extends 'hod_template/base_template.html' %}

{% block title %}
  Edit disease
{% endblock title %}

{% block page_title %}
  Edit disease
{% endblock page_title %}

{% block main_content %}
  {% load static %}

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <h2 class="card-header">Edit disease</h2>
            <div class="card-body">
              <form method="post" action="{% url 'clinic:edit_disease_record' disease.id %}">
                {% csrf_token %}
                <div class="row">
                  <div class="form-group col-sm-6">
                    <label for="Name" class="col-form-label">Name</label>
                    <input type="text" class="form-control" name="Name" id="Name" value="{{ disease.disease_name }}" placeholder="Enter name">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="code" class="col-form-label">code</label>
                    <input type="text" class="form-control" name="code" id="code" value="{{ disease.code }}" placeholder="Enter phone">
                  </div>
                </div>       
                
                <div class="form-group row">
                  <div class="offset-md-6 col-md-6 text-right">
                    <button type="submit" class="btn btn-primary">Save and Continue</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="card-footer">
              <div class="form-row">
                <div class="col-12">
                  {% if messages %}
                    {% for message in messages %}
                      <div class="alert {{ message.tags }}">
                        {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock main_content %}

clinic/templates/update/edit_insurance.html
{% extends 'hod_template/base_template.html' %}

{% block page_title %}
  Edit Insurance
{% endblock page_title %}

{% block main_content %}
  {% load static %}

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <h2 class="card-header">Edit Insurance</h2>
            <div class="card-body">
              <form method="post" action="{% url 'clinic:edit_insurance' insurance.id %}">
                {% csrf_token %}
                <div class="row">
                  <div class="form-group col-sm-6">
                    <label for="Name" class="col-form-label">Name</label>
                    <input type="text" class="form-control" name="Name" id="Name" value="{{ insurance.name }}" placeholder="Enter name">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="Phone" class="col-form-label">Phone</label>
                    <input type="tel" class="form-control" name="Phone" id="Phone" value="{{ insurance.phone }}" placeholder="Enter phone">
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-sm-6">
                    <label for="Short_name" class="col-form-label">Short name</label>
                    <input type="text" class="form-control" name="Short_name" id="Short_name" value="{{ insurance.short_name }}" placeholder="Enter short name">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="Email" class="col-form-label">Email</label>
                    <input type="email" class="form-control" name="Email" id="Email" value="{{ insurance.email }}" placeholder="Enter email" required>
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-sm-6">
                    <label for="Address" class="col-form-label">Address</label>
                    <input type="text" class="form-control" name="Address" id="Address" value="{{ insurance.address }}" placeholder="Enter address">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="website" class="col-form-label">Website</label>
                    <input type="url" class="form-control" name="website" id="website" value="{{ insurance.website }}" placeholder="Enter website url">
                  </div> 
                </div>
                <div class="form-group row">
                  <div class="offset-md-6 col-md-6 text-right">
                    <button type="submit" class="btn btn-primary">Save and Continue</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="card-footer">
              <div class="form-row">
                <div class="col-12">
                  {% if messages %}
                    {% for message in messages %}
                      <div class="alert {{ message.tags }}">
                        {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock main_content %}

clinic/templates/update/edit_staff.html
{% extends 'hod_template/base_template.html' %}

{% block page_title %}
  Edit Staff | Name: {{ staff.admin.username }} | ID: {{ staff.id }}
{% endblock page_title %}

{% block main_content %}
  {% load static %}

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- Left column -->
        <div class="col-md-12">
          <!-- General form elements -->
          <div class="card card-primary">
            <h2 class="card-header">Edit Staff</h2>
            <div class="card-body">
              <form id="editStaffForm" action="{% url 'clinic:edit_staff_save' %}" method="post" novalidate>
                {% csrf_token %}
                <!-- Personal Information -->
                <div class="row">
                  <div class="form-group col-sm-4">
                    <label for="firstName" class="col-form-label">First Name</label>
                    <input type="text" class="form-control" name="firstName" id="firstName" value="{{ staff.admin.first_name }}" required>
                    <div class="invalid-feedback">First name is required.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="middleName" class="col-form-label">Middle Name</label>
                    <input type="text" class="form-control" name="middleName" id="middleName" value="{{ staff.middle_name }}">
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="lastname" class="col-form-label">Last Name</label>
                    <input type="text" class="form-control" name="lastname" id="lastname" value="{{ staff.admin.last_name }}" required>
                    <div class="invalid-feedback">Last name is required.</div>
                  </div>
                </div>

                <!-- Professional Information -->
                <div class="row">
                  <div class="form-group col-sm-4">
                    <label for="profession" class="col-form-label">Select Profession</label>
                    <select class="form-control select2bs4" name="profession" id="profession" required>
                      <option value="">Select Profession</option>
                       <option value="doctor" {% if staff.profession == 'doctor' %}selected{% endif %}>Doctor</option>
                      <option value="nurse" {% if staff.profession == 'nurse' %}selected{% endif %}>Nurse</option>
                      <option value="pharmacist" {% if staff.profession == 'pharmacist' %}selected{% endif %}>Pharmacist</option>
                      <option value="developer" {% if staff.profession == 'developer' %}selected{% endif %}>Developer</option>
                      <option value="designer" {% if staff.profession == 'designer' %}selected{% endif %}>Designer</option>
                      <option value="manager" {% if staff.profession == 'manager' %}selected{% endif %}>Manager</option>
                      <option value="radiologist" {% if staff.profession == 'radiologist' %}selected{% endif %}>Radiologist</option>
                      <option value="lab_technician" {% if staff.profession == 'lab_technician' %}selected{% endif %}>Lab Technician</option>
                      <option value="receptionist" {% if staff.profession == 'receptionist' %}selected{% endif %}>Receptionist</option>
                      <option value="physiotherapist" {% if staff.profession == 'physiotherapist' %}selected{% endif %}>Physiotherapist</option>
                      <option value="accountant" {% if staff.profession == 'accountant' %}selected{% endif %}>Accountant</option>
                      <option value="security_guard" {% if staff.profession == 'security_guard' %}selected{% endif %}>Security Guard</option>
                      <option value="chef" {% if staff.profession == 'chef' %}selected{% endif %}>Chef</option>
                      <option value="cleaner" {% if staff.profession == 'cleaner' %}selected{% endif %}>Cleaner</option>
                     
                    </select>
                    <div class="invalid-feedback">Profession is required.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="maritalStatus" class="col-form-label">Marital Status</label>
                    <select class="form-control select2bs4" name="maritalStatus" id="maritalStatus" required>
                      <option value="">Select Marital Status</option>                    
                      <option value="single" {% if staff.marital_status == 'single' %}selected{% endif %}>Single</option>
                      <option value="married" {% if staff.marital_status == 'married' %}selected{% endif %}>Married</option>
                      <option value="divorced" {% if staff.marital_status == 'divorced' %}selected{% endif %}>Divorced</option>
                      <option value="widowed" {% if staff.marital_status == 'widowed' %}selected{% endif %}>Widowed</option>                    
                    </select>
                    <div class="invalid-feedback">Marital status is required.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="email" class="col-form-label">Email</label>
                    <input type="email" class="form-control" name="email" id="email" value="{{ staff.admin.email }}" required>
                    <div class="invalid-feedback">Email is required and should be valid.</div>
                  </div>
                </div>

                <div class="row">
                  <div class="form-group col-sm-4">
                    <label for="userRole" class="col-form-label">Select Role</label>
                    <select class="form-control select2bs4" name="userRole" id="userRole" required>
                      <option value="">Select Role</option>             
                      <option value="admin" {% if staff.role == 'admin' %}selected{% endif %}>Administrator</option>
                      <option value="doctor" {% if staff.role == 'doctor' %}selected{% endif %}>Doctor</option>
                      <option value="nurse" {% if staff.role == 'nurse' %}selected{% endif %}>Nurse</option>
                      <option value="physiotherapist" {% if staff.role == 'physiotherapist' %}selected{% endif %}>Physiotherapist</option>
                      <option value="labTechnician" {% if staff.role == 'labTechnician' %}selected{% endif %}>Lab Technician</option>
                      <option value="pharmacist" {% if staff.role == 'pharmacist' %}selected{% endif %}>Pharmacist</option>
                      <option value="receptionist" {% if staff.role == 'receptionist' %}selected{% endif %}>Receptionist</option>                   
                    </select>
                    <div class="invalid-feedback">Role is required.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="gender" class="col-form-label">Gender</label>
                    <select class="form-control select2bs4" name="gender" id="gender" required>
                      <option value="">Select Gender</option>
                      <option value="male" {% if staff.gender == 'male' %}selected{% endif %}>Male</option>
                      <option value="female" {% if staff.gender == 'female' %}selected{% endif %}>Female</option>
                      <option value="non-binary" {% if staff.gender == 'non-binary' %}selected{% endif %}>Non-Binary</option>
                      <option value="prefer-not-to-say" {% if staff.gender == 'prefer-not-to-say' %}selected{% endif %}>Prefer Not to Say</option>                    
                    </select>
                    <div class="invalid-feedback">Gender is required.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="dob" class="col-form-label">Date of Birth</label>
                    <input type="date" class="form-control" id="date_of_birth" name="date_of_birth" value="{{ staff.date_of_birth|date:'Y-m-d' }}" required>
                    <div class="invalid-feedback">Date of birth is required.</div>
                  </div>
                </div>

                <div class="row">
                  <div class="form-group col-sm-4">
                    <label for="phone" class="col-form-label">Phone</label>
                    <input type="tel" class="form-control" id="phone" name="phone" value="{{ staff.phone_number }}" required pattern="(0|\+255)\d{9,12}" title="Please enter a valid phone number starting with '0' or '+255' and having 10 to 13 digits">
                    <div class="invalid-feedback">Please enter a valid phone number starting with '0' or '+255' and having 10 to 13 digits.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="Workingplace" class="col-form-label">Working place</label>
                    <select class="form-control select2bs4" name="Workingplace" id="Workingplace" required>
                      <option value="">Select Working place</option>                     
                      <option value="resa" {% if staff.work_place == 'resa' %}selected{% endif %}>Resa</option>
                      <option value="kahama" {% if staff.work_place == 'kahama' %}selected{% endif %}>Kahama</option>                
                    </select>
                    <div class="invalid-feedback">Working place is required.</div>
                  </div>
                  <div class="form-group col-sm-4">
                    <label for="joiningDate" class="col-form-label">Joining Date</label>
                    <input type="date" class="form-control" name="joiningDate" id="joiningDate" value="{{ staff.joining_date|date:'Y-m-d' }}" required>
                    <div class="invalid-feedback">Joining date is required.</div>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="offset-md-6 col-md-6 text-right">
                    <button type="submit" class="btn btn-primary">Save and Continue</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="card-footer">
              <div class="form-row">
                <div>
                  {% if messages %}
                    <div class="col-12">
                      {% for message in messages %}
                        {% if message.tags == 'error' %}
                          <div class="alert alert-danger">{{ message }}</div>
                        {% elif message.tags == 'success' %}
                          <div class="alert alert-primary">{{ message }}</div>
                        {% endif %}
                      {% endfor %}
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script>
    (function() {
      'use strict';
      window.addEventListener('load', function() {
        var form = document.getElementById('editStaffForm');
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      }, false);
    })();
  </script>

{% endblock main_content %}